import { test, expect, create, waitShape, resetWorld, world, API, ADMIN } from './helpers.ts'
test.beforeEach(async ({ request }) => { await resetWorld(request) })
test('A text → B rectangle → move → delete → refresh both → zero-client persistence', async ({ peer, request }) => {
  const a = await peer(), b = await peer()
  const text = await create(a.page, 'text', 'Hello from A'); await waitShape(b.page, text)
  const rectangle = await create(b.page, 'rectangle'); await waitShape(a.page, rectangle)
  await a.page.evaluate(id => window.__CANVAS_TEST__!.move(id, 333, -222), rectangle)
  await expect.poll(() => b.page.evaluate(id => window.__CANVAS_TEST__!.shapes().find(shape => shape.id === id)?.x, rectangle)).toBe(333)
  await b.page.evaluate(id => window.__CANVAS_TEST__!.remove(id), text); await waitShape(a.page, text, false)
  for (const page of [a.page, b.page]) { await page.reload(); await page.waitForFunction(() => !!window.__CANVAS_TEST__); await waitShape(page, rectangle); await waitShape(page, text, false) }
  await a.context.close(); await b.context.close()
  const c = await peer(); await waitShape(c.page, rectangle); await waitShape(c.page, text, false)
  const saved = await world(request)
  expect(saved.snapshot.documents.some((item: { state: { typeName: string } }) => ['asset', 'user', 'instance_presence'].includes(item.state.typeName))).toBe(false)
})
test('independent concurrent edits remain and local undo does not undo another user', async ({ peer }) => {
  const a = await peer(), b = await peer()
  const [rect, text] = await Promise.all([create(a.page, 'rectangle'), create(b.page, 'text', 'Independent B')])
  await waitShape(a.page, text); await waitShape(b.page, rect)
  await a.page.evaluate(() => window.__CANVAS_TEST__!.undo())
  await waitShape(a.page, rect, false); await waitShape(b.page, rect, false)
  await waitShape(a.page, text); await waitShape(b.page, text)
  await a.page.evaluate(() => window.__CANVAS_TEST__!.redo()); await waitShape(b.page, rect)
  await Promise.all([a.page.evaluate(id => window.__CANVAS_TEST__!.move(id, 321, 100), rect), b.page.evaluate(id => window.__CANVAS_TEST__!.move(id, -432, 0), text)])
  await expect.poll(() => a.page.evaluate(id => window.__CANVAS_TEST__!.shapes().find(shape => shape.id === id)?.x, text)).toBe(-432)
  await expect.poll(() => b.page.evaluate(id => window.__CANVAS_TEST__!.shapes().find(shape => shape.id === id)?.x, rect)).toBe(321)
})
test('disconnected client pauses edits, reconnects and receives independent changes', async ({ peer }) => {
  const a = await peer(), b = await peer()
  const first = await create(a.page, 'rectangle'); await waitShape(b.page, first)
  await b.context.setOffline(true)
  await b.page.evaluate(() => { for (const ws of window.__TEST_SOCKETS__ ?? []) ws.close(4000, 'Test network interruption') })
  await expect(b.page.getByText(/editing is paused/i)).toBeVisible()
  const second = await create(a.page, 'text', 'While B was offline')
  await b.context.setOffline(false)
  await expect(b.page.getByRole('status').filter({ hasText: /^Live$/ })).toBeVisible()
  await waitShape(b.page, second)
  const third = await create(b.page, 'ellipse'); await waitShape(a.page, third)
})
test('presence appears, rename synchronizes, and disconnected collaborators disappear', async ({ peer }) => {
  const a = await peer(), b = await peer()
  await expect.poll(() => a.page.evaluate(() => window.__CANVAS_TEST__!.people())).toBe(1)
  await b.page.getByRole('button', { name: 'Canvas menu and presence' }).click()
  await b.page.getByLabel('Display name', { exact: true }).fill('Guest Aurora')
  await b.page.getByRole('button', { name: 'Save', exact: true }).click()
  await a.page.getByRole('button', { name: 'Canvas menu and presence' }).click()
  await expect(a.page.locator('.people-list')).toContainText('Guest Aurora')
  await b.context.close()
  await expect.poll(() => a.page.evaluate(() => window.__CANVAS_TEST__!.people()), { timeout: 25000 }).toBe(0)
})
test('owner backup/restore survives destructive edits and rejects stale restore clocks', async ({ peer, request }) => {
  const a = await peer(), id = await create(a.page, 'text', 'Recover me')
  await expect.poll(async () => (await world(request)).snapshot.documents.some((item: { state: { id: string } }) => item.state.id === id)).toBe(true)
  const metadata = await (await request.post(`${API}/api/admin/snapshots`, { headers: { Authorization: `Bearer ${ADMIN}` } })).json()
  const backup = await (await request.get(`${API}/api/admin/snapshots/${metadata.id}`, { headers: { Authorization: `Bearer ${ADMIN}` } })).json()
  await a.page.evaluate(id => window.__CANVAS_TEST__!.remove(id), id)
  await expect.poll(async () => (await world(request)).snapshot.documents.some((item: { state: { id: string } }) => item.state.id === id)).toBe(false)
  const openRestore = await request.post(`${API}/api/admin/restore`, { headers: { Authorization: `Bearer ${ADMIN}`, 'If-Match': '0' }, data: backup }); expect(openRestore.status()).toBe(409)
  await a.context.close()
  await expect(async () => {
    const info = await (await request.get(`${API}/api/admin/snapshots`, { headers: { Authorization: `Bearer ${ADMIN}` } })).json()
    const restored = await request.post(`${API}/api/admin/restore`, { headers: { Authorization: `Bearer ${ADMIN}`, 'If-Match': String(info.clock) }, data: backup })
    expect(restored.status()).toBe(200)
  }).toPass({ timeout: 25000 })
  const b = await peer(); await waitShape(b.page, id)
})
test('ten real contexts converge without repeated-session message loops', async ({ peer, browserName }) => {
  test.skip(browserName !== 'chromium', 'Ten-client load is run once in Chromium; functional collaboration runs in all browsers.')
  test.setTimeout(120000)
  const peers = []
  for (let index = 0; index < 10; index++) peers.push(await peer())
  const ids = await Promise.all(peers.map((p, index) => create(p.page, 'rectangle', '', index * 140, 0)))
  for (const p of peers) {
    await expect.poll(() => p.page.evaluate(() => window.__CANVAS_TEST__!.shapes().length)).toBe(10)
    await expect.poll(() => p.page.evaluate(() => window.__CANVAS_TEST__!.people())).toBe(9)
  }
  expect(new Set(ids).size).toBe(10)
})
