import test from 'node:test'
import assert from 'node:assert/strict'
import { loadIdentity, cleanName, colorForId, IDENTITY_KEY, saveIdentity } from '../../app/presence/identity.ts'
import { loadTheme } from '../../app/storage/preferences.ts'
import { createLiveConfig, DEFAULT_SUPABASE_PUBLISHABLE_KEY, DEFAULT_SUPABASE_URL, normalizeBasePath } from '../../app/config/public-config.ts'
function memory() { const map = new Map<string, string>(); return { getItem: (key: string) => map.get(key) ?? null, setItem: (key: string, value: string) => { map.set(key, value) } } }
const id = 'ec4145a1-f218-416e-bdb5-a5f79a5f03c0'
test('anonymous identity persists locally and color is deterministic', () => { const storage = memory(), first = loadIdentity(storage, () => id); assert.equal(first.deviceId, id); assert.match(first.displayName, /^Guest \d{4}$/); assert.deepEqual(loadIdentity(storage, () => { throw new Error('Must reuse ID') }), first); assert.equal(first.color, colorForId(id)) })
test('corrupt local identity safely regenerates, without a login flow', () => { const storage = memory(); storage.setItem(IDENTITY_KEY, '{broken'); assert.equal(loadIdentity(storage, () => id).deviceId, id) })
test('names are bounded and sanitized, not authenticated', () => { assert.equal(cleanName('\n Jonathan\u0000 '), 'Jonathan'); assert.equal(cleanName('a'.repeat(100)).length, 32); assert.equal(cleanName('  '), 'Guest') })
test('unavailable browser storage does not prevent use', () => { const storage = { getItem: () => { throw new Error('disabled') }, setItem: () => { throw new Error('disabled') } }; const identity = loadIdentity(storage, () => id); assert.equal(identity.deviceId, id); assert.equal(saveIdentity(storage, identity), false) })
test('Canvas is light-only and ignores legacy saved theme values', () => { const storage = memory(); assert.equal(loadTheme(storage), 'light'); storage.setItem('canvas.theme.v1', 'dark'); assert.equal(loadTheme(storage), 'light'); storage.setItem('canvas.theme.v1', 'system'); assert.equal(loadTheme(storage), 'light'); storage.setItem('canvas.theme.v1', 'anything'); assert.equal(loadTheme(storage), 'light') })
test('live config uses public Supabase defaults and permits only the CI table override', () => { assert.deepEqual(createLiveConfig(undefined, undefined), { supabaseUrl: DEFAULT_SUPABASE_URL, supabaseKey: DEFAULT_SUPABASE_PUBLISHABLE_KEY, tableName: 'canvas_elements' }); assert.equal(createLiveConfig(DEFAULT_SUPABASE_URL, DEFAULT_SUPABASE_PUBLISHABLE_KEY, 'canvas_ci_elements').tableName, 'canvas_ci_elements') })
test('live config rejects unsafe origins, invalid keys and unknown tables', () => { for (const url of ['http://example.com', 'not a URL', 'https://a:b@example.com', 'https://example.com/api', 'https://example.com?key=x']) assert.throws(() => createLiveConfig(url, 'public-key')); assert.equal(createLiveConfig('https://example.com', '').supabaseKey, DEFAULT_SUPABASE_PUBLISHABLE_KEY); assert.throws(() => createLiveConfig('https://example.com', 'x'.repeat(513))); assert.throws(() => createLiveConfig('https://example.com', 'public-key', 'other')) })
test('Pages base path supports repository and custom-domain roots', () => { assert.equal(normalizeBasePath('/canvas'), '/canvas/'); assert.equal(normalizeBasePath('/'), '/'); for (const path of ['canvas', '/a/../b', '/a?b', '/a#b', '/a\\b']) assert.throws(() => normalizeBasePath(path)) })
